server:
  port: 8080
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/mysql?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
logging:
  level:
    com: debug